ch05/jumpstartrails/config/routes.rb
Jumpstartrails::Application.routes.draw do
  
  get "posts/index"
  get "posts/show"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pages
  resources :posts

  %w[about contact cv].each do |page|
    get page, :controller => 'pages', :action => page
  end

  root "pages#index"

  

end

ch05/jumpstartrails/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

ch05/jumpstartrails/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title, :slug, :description
  has_many :posts
end

ch05/jumpstartrails/app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :title, :slug, :content
  validates :title, presence: true, length: {minimum: 5}
  validates :slug, presence: true, format: {with: /\A[a-zA-Z-]+\z/, message: "Only letters allowed"}
  validates :content, presence: true, length: {minimum: 100}

  
end

ch05/jumpstartrails/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :slug, :blurb, :content, :category_id, :image
  belongs_to :category
  scope :rails, -> {where(category_id: 1)}
  extend FriendlyId
  friendly_id :title, use: :slugged
  mount_uploader :image, ImageUploader
end

ch05/jumpstartrails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ch05/jumpstartrails/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    @page.save!
    redirect_to action: :show, id: @page.id
  end

  def show
  end

  def about
   @page = Page.where(slug: 'about').first
  end

  private

  def set_page
    @page = Page.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :slug, :content)
  end
end

ch05/jumpstartrails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
    @latest = Post.last
  end

  def show
    @post = Post.find(params[:id])
  end
end

ch05/jumpstartrails/app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path, force_active = false)
    class_name = (force_active || current_page?(link_path)) ? 'active' : ''
    content_tag(:li, :class => class_name) do
      link_to link_text, link_path
    end
  end
end

ch05/jumpstartrails/app/helpers/pages_helper.rb
module PagesHelper
end

ch05/jumpstartrails/app/helpers/posts_helper.rb
module PostsHelper
end

ch05/jumpstartrails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jumpstartrails</title>
  <%= metamagic title: "My default title", 
    description: "My default description.", 
    keywords: %w(rails ruby Ruby on Rails) %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

ch05/jumpstartrails/app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= metamagic title: "JumpStart Rails", description: "The JumpStart Rails app", keywords: %w(rails ruby Ruby on Rails) %>
  <%= stylesheet_link_tag    "pages", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css"/>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

      <div class="masthead">
        <h3 class="muted">Jump Start Rails</h3>
        <div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <ul class="nav">
                <%= nav_link 'Home', root_path %>
                <%= nav_link 'About', about_path %>
                <%= nav_link 'Blog', posts_path %>
              </ul>
            </div>
          </div>
        </div><!-- /.navbar -->
      </div>

    <%= yield %>
    <hr>

  <div class="footer">
    <p>&copy; Jump Start Rails 2013</p>
  </div>
</div> <!-- /container -->

</body>
</html>

ch05/jumpstartrails/app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= metamagic title: "JumpStart Rails", description: "The JumpStart Rails app", keywords: %w(rails ruby Ruby on Rails) %>
  <%= stylesheet_link_tag    "posts", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <div class="masthead">
    <h3 class="muted">Jump Start Rails</h3>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <ul class="nav">
                <%= nav_link 'Home', root_path %>
                <%= nav_link 'About', about_path %>
                <%= nav_link 'Blog', posts_path, true %>
              </ul>
          </div>
        </div>
      </div><!-- /.navbar -->
    </div>

    <%= yield %>
    <hr />
    <div class="footer">
      <p>&copy; Jump Start Rails 2013</p>
    </div>
  </div> <!-- /container -->

</body>
</html>

ch05/jumpstartrails/app/views/pages/about.html.erb
<p><%= @page.content.html_safe %></p>

ch05/jumpstartrails/app/views/pages/index.html.erb
<h1>Listing pages</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @pages.each do |page| %>
    <tr>
      <td><%= page.title %></td>
      <td><%= page.slug %></td>
      <td><%= page.content %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "New Page", new_page_path %>

ch05/jumpstartrails/app/views/pages/new.html.erb
<%= form_for(@page) do |f| %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

ch05/jumpstartrails/app/views/pages/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @page.slug %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

ch05/jumpstartrails/app/views/posts/index.html.erb
<div class="hero-unit">
    <h2>Latest post: <%= @latest.title %></h2>
    <p><%= @latest.blurb %></p>
    <p>
        <%= link_to 'Read Post', @latest, :class => "btn btn-primary btn-large" %>
    </p>
</div>
<h1>Posts</h1>

<table class="table table-bordered">
  <% @posts.each do |post| %>
  <tr>
    <td style="width:100px;"><%= image_tag post.image_url(:thumb).to_s %></td>
      <td>
        <div>
          <strong><%= post.title %></strong><br />
            <p class="blurb_target">
              <a href="#">Show/hide blurb</a>
            </p>
         </div>
         <p class="blurb_content"><%= post.blurb %></p>
         <%= link_to 'Read Post', post %>
      </td>
    </tr>
  <% end %>
</table>
<a href="#" id="test_click">Just testing</a>

ch05/jumpstartrails/app/views/posts/show.html.erb
<%
meta :title => @post.title,
     :description => @post.blurb,
     :keywords => %w(rails ruby on rails Rails jump start rails)
%>
<p>
  <strong>Title:</strong> <%= @post.title %>
</p>
<p>
  <p class='pull-left'><%= image_tag @post.image_url.to_s %></p>
</p>
<p>
  <%= @post.content %>
</p>

<%= link_to "Back", posts_path %>